:PROPERTIES:
:ROAM_REFS: @anginer2018corporate
:ID:       ff3cea32-3b50-45aa-a076-51a987e3cc89
:mtime:    20220116200601 20220116104808
:ctime:    20220116104808
:END:
#+TITLE: Corporate governance of banks and financial stability

#+filetags: :公司治理:thesis:
#+bibliography: ../reference.bib
[[https://www.sciencedirect.com/science/article/pii/S0304405X18301715][Corporate governance of banks and financial stability]]

* 主题
对于股东，银行可以从风险不敏感存款保险形式的明确国家担保中受益，也可以从流动性和资本支持形式的潜在隐性担保中受益，以防止其倒闭。金融安全网代表了公共当局提供的看跌期权。这种看跌期权的价值增加了​银行活动的风险和银行杠杆。此外，如果在多家银行倒闭的情况下更有可能触发国家担保，银行就有动力去从众并承担相关（或系统性）风险。因此，银行股东可以从承担更多的独立风险和系统性风险中受益，随着股东试图将风险转移到纳税人身上，随着金融安全网的加强，额外风险承担的好处也会增加。

对于经理人，更倾向于规避风险的经理。与可能持有多元化股票投资组合的股东不同，经理可以将他们的工作、声誉以及个人财富的很大一部分与公司的业绩和健康联系起来。

公司治理是解决股东和经理之间承担风险的潜在冲突的关键决定因素。
* 数据
对 1990 年至 2014 年期间的美国银行样本和 2004 年至 2008 年期间的国际银行样本，实证检验了银行公司治理与风险之间的关系。

** 风险

非系统性银行风险使用违约距离、杠杆率和资产波动性度量

系统性风险利用与[cite/text:@2020Do]相似的 CoVaR 、 marginal expected shortfall 度量

** 公司治理
*** Governance
[cite/text/c:@aggarwal2009differences] 基于 44 个与董事会规模和组成、薪酬和所有权、外部审计和反收购措施相关的个人治理属性构成的指标
*** Entrenchment
[cite/text:@bebchuk2009matters] 显示管理层对股东的权力
*** Independence
独立董事的占比
* 分析方法
Size 是总资产的对数

\(risk=\beta_1 Size +\beta_2 Gov + \beta_3 Size \cdot Gov\) 的 \beta_3 小于 0

再通过三重差分将大型银行与大型非金融公司进行比较，在银行业治理和风险承担之间发现的“大到不能倒”的关系在非金融部门中并不存在。
* 模型
加入公司固定效应面板减少公司治理的内生性。

工具变量对同一国家和同一年所有非金融公司的该变量的平均值来衡量银行的治理变量。认为这样的国家年平均值是一种有效的工具变量，因为对银行风险的冲击不太可能影响非金融公司的公司治理。

* 结论
相对于非银行机构，一个标准差治理变量的增加使银行的违约距离指标降低了 0.35（或 0.14 个标准差）

使用美国数据，发现与非金融公司相比，对股东有利的公司治理与银行的独立和系统性风险之间存在更强的关系，因为银行是金融安全网的主要受益者。大型银行的风险与股东友好型公司治理之间的关系更强，这与受益于“大到不能倒”担保的大型银行一致。
在金融安全网更慷慨的国家，对股东友好的公司治理随着银行独立风险和系统性风险的变化更为积极。
#+print_bibliography:
