:PROPERTIES:
:ROAM_REFS: @chen2018quantifying
:ID:       625f79be-aea0-470c-acf4-ae7dd2482bd4
:mtime:    20220116200414 20220116104808
:ctime:    20220116104808
:END:
#+TITLE: Quantifying liquidity and default risks of corporate bonds over the business cycle

#+filetags: :行业周期:流动性:thesis:
#+bibliography: ../reference.bib
[[https://www.nber.org/system/files/working_papers/w20638/w20638.pdf][Quantifying liquidity and default risks of corporate bonds over the business cycle]]

* 主题
[cite:@longstaff2005corporate] 估计“non-default components” 占利差AAA 或 AA 的约 50%，Baa 的30%，且 non-default components of credit spreads are strongly related to measures of bond liquidity
* 数据
* 分析方法
流动性与评级/经济周期
1) corporate bonds with higher credit ratings tend to be more liquid;
2) corporate bonds are less liquid during economic downturns, especially for riskier bonds

一二级市场上的交互：
一方面，违约风险对公司债券的交易顺差和流动性折价有至关重要的影响。另一方面，更大的流动性折扣使公司对到期债务进行展期的成本更高，从而增加了违约的可能性。
当二级市场流动性恶化时，股权持有人更有可能违约，这反过来又会进一步恶化二级债券市场的流动性，以此类推。
* 模型
在公司债券的结构模型中建立了场外搜索摩擦。
在模型中，企业违约决策与时变的宏观经济和二级市场流动性状况相互作用。

根据违约概率的历史时刻、债券收益率和流动性的实证指标对模型进行了校准。该模型能够匹配公司债券在不同评级等级和集合体上的条件观测信用利差，以及以前文献中研究的各种非违约成分的度量，我们提出了一个结构分解，该结构分解捕捉了企业债券在整个商业周期中流动性和违约风险的交互作用，并使用这个框架来评估衰退期间流动性供应政策的效果。
* 结论
the interactions between liquidity and default risk account for 2540% of the observed credit spreads and up to 55% of the credit spread changes over the business cycle.As an application, we use this framework to quantitatively evaluate the effects of liquidity-provision policies for the corporate bond market
#+print_bibliography:
