:PROPERTIES:
:ROAM_REFS: @nickerson2017debt
:ID:       ffb63e1c-0335-48e8-aedf-f51eff80b200
:mtime:    20220116200553 20220116104808
:ctime:    20220116104808
:END:
#+TITLE: Debt correlations in the wake of the financial crisis: what are appropriate default correlations for structured products?

#+filetags: :风险传染:thesis:
#+bibliography: ../reference.bib
[[https://www.sciencedirect.com/science/article/pii/S0304405X17301289][Debt correlations in the wake of the financial crisis: what are appropriate default correlations for structured products?]]

* 主题
结构化产品之间存在关联性，风险通过结构化产品如 MBS 、CDO 传染

我们记录了评级机构假设的违约相关性，将他们的假设与我们的估计进行了对比，并量化了纳入脆弱因素[cite:@duffie2009frailty]的违约相关性估计对实际AAA级高级CDO部分的适当规模的影响。
#+begin_quote
  an unobservable time-varying factor referred to as ‘frailty’ can significantly help in explaining default clustering.
#+end_quote

* 分析方法
对于金融危机(1986年至2006年)之前的公司债券，当仅使用国家相关评级转移矩阵时，我们估计的两两违约相关性仅为0.002。然而，当只考虑模型脆弱性时，平均成对债券违约相关性跃升至0.086。这些违约相关性是危机前评级机构用于CLO的8倍以上。此外，将评级变化和模型脆弱性都包括在内，将平均违约相关性提高到0.10。如果纳入金融危机中包含的信息，并使用截至2012年12月的样本对模型进行估计，这一估计值将增加约25%，至0.125。总体而言，我们的研究结果表明，联合考虑可观察到的风险因素和脆弱性的共同移动可以为违约分布的右尾增加相当大的厚度。
* 模型
现有文献主要通过对 /违约强度/ 或资产寿命的相关性进行建模来检验多种资产的联合信用风险。这些方法的一个优点是它们能够从实现资产违约的特定时间范围中抽象出来。虽然这些技术有助于从广义上研究联合信用风险，但这种方法的局限性在于难以将由此产生的估计应用于一组特定资产的联合违约风险，通常还依赖于双重随机假设，即以观察到的风险因素路径为条件，已实现的违约是独立的。
* 结论
#+print_bibliography:
