:PROPERTIES:
:ROAM_REFS: @subrahmanyam2017credit
:ID:       e58da907-9765-4974-8b53-62ac38e6e360
:mtime:    20220116200610 20220116104808
:ctime:    20220116104808
:END:
#+TITLE: Credit default swaps, exacting creditors and corporate liquidity management

#+filetags: :风险传染:公司治理:thesis:
#+bibliography: ../reference.bib
[[https://www.sciencedirect.com/science/article/pii/S0304405X17300247][Credit default swaps, exacting creditors and corporate liquidity management]]

* 主题
虽然 CDS 目前（信用风险缓释合约 CRMA 、信用风险缓释凭证 CRMW ）应用很小，但是交叉违约条款导致违约的也挺常见。

引入 CDS 交易后，高现金现象与高杠杆现象并存。

* 数据
因变量是现金和有价证券与总资产的比率

自变量包括行业现金流风险（Industry sigma）、现金流与总资产的比率（Cash flow/Assets）、衡量投资机会的指标（Market to book）、总资产的对数（Size）、营运资本比率（Net working capital/Assets）、资本支出（Capital Spend）、杠杆（Leverage）、研发与销售的比率 （R&D/Sales）、股息支付（ Dividend dummy ）、收购占总资产的比率（ Acquisition activity ）、占国外税前收入的比例（ Foreign pretax income ）。
* 分析方法
CDS 的收益和成本之间存在矛盾关系
1. CDS 有助于增加当前的信贷供应，因为债权人可以将部分信用风险转移到 CDS 市场。引入 CDS 后债权人的监控可能不那么严格。在这种情况下，借款公司可能会进行风险转移并减少持有具有高机会成本的现金以最大化股权价值；
2. CDS 的存在可能会改变债权人和借款人之间的关系，并对借款人施加未来的融资约束或成本。事后，受 CDS 保护的债权人在重新谈判的过程中往往更加强硬，这增加了公司对流动性的预防性需求。

影响途径是
1. 公司的预防考虑，如信用风险恶化和派息
2. 借款人的风险转移激励
* 模型
CDS 交易可能是内生的。有可能存在一个不可观察的变量来推动 CDS 交易的引入和公司现金持有

工具变量为公司在其债务上引入 CDS 交易的潜在倾向，具体为 Lender FX usage [cite:@saretto2013corporate] & Lender Tier 1 capital [cite:@subrahmanyam2014does]
* 结论
现金持有的最佳水平取决于现金的边际价值。

在 CDS 交易开始后，有关公司持有更多的现金来偿还债务。对于不支付股息且流动性边际价值较高的 CDS 公司，现金持有量的增加更为明显。对于现金流波动较大的 CDS 公司，这些增加的现金持有量并降低杠杆率。总体而言，CDS 公司采用更保守的流动性政策以避免与更严格的债权人谈判的观点一致。
#+print_bibliography:
